server:
  port: 8080
  baseURL: "/"

auth:
  tokenExpirationHours: 2
  methods:
    chainfs:
      enabled: true
      apiBaseUrl: "https://nansendev.azurewebsites.net"
      createUser: true
      adminClaim: "roles"
      adminClaimValue: "admin"
    password:
      enabled: false
    oidc:
      enabled: false
    proxy:
      enabled: false
    noauth: false

userDefaults:
  permissions:
    admin: false
    modify: true
    share: true
    delete: true
    create: true
    download: true
