server:
  port: 8080
  baseURL: "/"
  sources:
    - path: "/srv"

auth:
  key: "fb-chainfs-dev-key-32bytes-xxyyz" # Exactly 32 bytes for AES-256
  tokenExpirationHours: 2
  methods:
    chainfs:
      enabled: true
      apiBaseUrl: "https://nansendev.azurewebsites.net"
      clientSecret: "oMe8Q~2Q0nmGM1zpBG_.WPT5yQseLo1PI6lxCc.N"
      createUser: true
      adminClaim: "roles"
      adminClaimValue: "admin"
    password:
      enabled: false
    oidc:
      enabled: false
    proxy:
      enabled: false
    noauth: false

userDefaults:
  permissions:
    admin: false
    modify: true
    share: true
    delete: true
    create: true
    download: true
